# -*- coding: utf-8 -*-
"""Aula BES IA - Sistemas fuzzy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MRr0va7EX8h2lIAxumfJNYwWcctTgIih
"""

#Bibioteca
#pip install scikit-fuzzy
#pip install packaging
#pip install networkx
#pip install matplotlib

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

#  antecedente / variaveis linguisticas
qualidade = ctrl.Antecedent(np.arange(0, 11, 1), 'qualidade')
servico = ctrl.Antecedent(np.arange(0, 11, 1), 'servico')
gorjeta = ctrl.Consequent(np.arange(0, 26, 1), 'gorjeta')

# função de pertinência (3, 5, or 7)
qualidade.automf(3, names=['ruim','boa','saborosa'])
servico.automf(3, names=['ruim','aceitável','ótimo'])
#servico.automf(3)

# Customizando as funções de pertinência
gorjeta['baixa'] = fuzz.trimf(gorjeta.universe, [0, 0, 13])
gorjeta['media'] = fuzz.trimf(gorjeta.universe, [0, 13, 25])
gorjeta['alta'] = fuzz.trimf(gorjeta.universe, [13, 25, 25])

"""view"""

# visualização das funções de pertinência
#qualidade['boa'].view()
qualidade.view()
servico.view()

gorjeta.view()

# Regras
regra1 = ctrl.Rule(qualidade['ruim'] | servico['ruim'], gorjeta['baixa'])
regra2 = ctrl.Rule(servico['aceitável'], gorjeta['media'])
regra3 = ctrl.Rule(servico['ótimo'] | qualidade['saborosa'], gorjeta['alta'])

regra1.view()
regra2.view()
regra3.view()

"""Criação do sistema de controle e simulação"""

regras = ctrl.ControlSystem([regra1, regra2, regra3])
sistema_fuzzy = ctrl.ControlSystemSimulation(regras)

"""Exemplo: taxa de qualidade 6.5 de 10 e serviço 9.8 de 10."""

# Testando
sistema_fuzzy.input['qualidade'] = 6.5
sistema_fuzzy.input['servico'] = 9.8

# Computando
sistema_fuzzy.compute()

"""Resultado e visualização do conjunto fuzzy gorjeta


"""

print (sistema_fuzzy.output['gorjeta'])
gorjeta.view(sim=sistema_fuzzy)

"""Referência:

https://scikit-fuzzy.readthedocs.io/en/latest/auto_examples/plot_tipping_problem_newapi.html
"""

input()